Simulation = "dfinity"
Servers = 2
Bf = 3
Rounds = 50
Suite = "bn256.G2"
Delay = 100
Seed = 123456789
BeaconNb = 1
BlockMakerNb = 2
NotarizerNb = 3
Threshold = 3
BlockSize = 100
BlockTime = 500 
FinalizeTime = 500

Hosts
6
